input_data_path: "data/heart_cleveland_upload.csv"
output_model_path: "models/model.pkl"
metric_path: "models/metrics.json"
# downloading_params:
#   s3_bucket: for-dvc
#   paths:
#     - train.csv
#     - test.csv
#   output_folder: "data/raw/"
splitting_params:
  val_size: 0.2
  random_state: 3
train_params:
  model_type: "LogisticRegression"
feature_params:
  categorical_features:
    - 'sex'
    - 'cp'
    - 'fbs'
    - 'restecg'
    - 'exang'
    - 'slope'
    - 'ca'
    - 'thal'
  numerical_features:
    - 'age'
    - 'trestbps'
    - 'chol'
    - 'thalach'
    - 'oldpeak'
  target_col: 'condition'
  features_to_drop: []



