input_data_path: 'data/heart_cleveland_upload.csv'
output_model_path: 'models/model.pkl'
metric_path: 'models/val_metrics.json'

splitting_params:
  val_size: 0.20 
  random_state: 42 

train_params:
  model_type: 'LogisticRegression' 
  random_state: 42

feature_params:
  categorical_features:
    - 'sex'
    - 'cp'
    - 'fbs'
    - 'restecg'
    - 'exang'
    - 'slope'
    - 'ca'
    - 'thal'
  numerical_features:
    - 'age'
    - 'trestbps'
    - 'chol'
    - 'thalach'
    - 'oldpeak'
  target_col: 'condition'
  features_to_drop: []
